---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Create cert directory
  command: "{{ item }}"
  with_items:
   - sudo mkdir -p /etc/docker/certs.d/server-3:5000
   - sudo mkdir -p /etc/certs

- name: Copy cert1
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../certs/ca.crt"
    dest: /etc/certs

- name: Copy key1
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../certs/ca.key"
    dest: /etc/certs

- name: Copy cert
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../certs/ca.crt"
    dest: /etc/docker/certs.d/server-3:5000/

- name: Copy key
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../certs/ca.key"
    dest: /etc/docker/certs.d/server-3:5000/

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - kubectl=1.19.1-00
      - apache2-utils

- name: Setup kubeconfig for vagrant user
  become: False
  command: "{{ item }}"
  with_items:
   - mkdir -p /home/vagrant/.kube
   - scp -r -o StrictHostKeyChecking=no vagrant@192.168.50.10:/home/vagrant/.kube/* /home/vagrant/.kube/
   - sudo chmod -R 777 /home/vagrant/.kube
   - sudo cp -r /home/vagrant/.kube /var/lib/jenkins

- name: Run Registry
  ansible.builtin.command: docker run -d -p 5000:5000 --restart=always --name registry -v /etc/certs:/etc/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/etc/certs/ca.crt -e REGISTRY_HTTP_TLS_KEY=/etc/certs/ca.key registry
  ignore_errors: yes

- name: Setup kubeconfig for jenkins
  become: False
  command: "{{ item }}"
  with_items:
   - sudo cp -r /home/vagrant/.kube /var/lib/jenkins
